name: Continuous Integration
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make gradlew executable
        run: |
          chmod +x gradlew  # Ensure gradlew is executable
          ls -l gradlew     # List permissions for debugging
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle build
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/distributions/*
            build/reports/*
